### ISSUE TITLE
Increase in Crashes since android 13 

### ISSUE THREAD

**Issue by eomene** [getsentry/sentry-unity#1469]
### Environment

How do you use Sentry?
Sentry SaaS (sentry.io) or self-hosted/on-premise (which version?)
Saas

Which version of the SDK?
1.6.0

How did you install the package? (Git-URL, Assetstore)
git url

Which version of Unity?
2021.3.31

Is this happening in Unity (editor) or on a player like Android, iOS, Windows?
Android

### Steps to Reproduce
We really cant. Its random, but the crashes all have sentry in them. Multiple variations of it. Not sure if it happens when trying to get other errors in our game. They all started going up around Sept 12th

We get a hard crash and the crashes have been significantly increasing recently. Without any new release. We updated the plugin and this has not helped. There is really nothing else we can share than this 

### Any logs or screenshots
<img width="1487" alt="Screenshot 2023-10-13 at 15 55 43" src="https://github.com/getsentry/sentry-unity/assets/16381081/dd698d87-c478-4f6b-a1c5-d22acc0577df">

**Comment by alfbbtech** [comment]
Same problem, identical, same everything

**Comment by bitsandfoxes** [comment]
Thanks for reaching out! This sounds an awful lot like https://github.com/getsentry/sentry-java/issues/2955

**Comment by alfbbtech** [comment]
Removed Sentry, lol, no crashes

**Comment by bitsandfoxes** [comment]
Hey @eomene, can you share the actual event with me? Either here or stefan@sentr.io
Thanks!

**Comment by andrey-vishnitskiy-hypemasters** [comment]
I got the same scenario, got a crash rate 5 times less after removing Sentry

Unity 2020.3.43 and 2020.3.48

Affects Android 12, 13 (no affect on 9, 10, 11)

Also, it has a dramatic increase in crash rate together with IronSource SDK

![CleanShot 2023-10-19 at 16 20 20@2x](https://github.com/getsentry/sentry-unity/assets/138811311/3747c7a7-4eaf-46dd-a33c-14819fa23848)

**Comment by eomene** [comment]
> Hey @eomene, can you share the actual event with me? Either here or [stefan@sentr.io](mailto:stefan@sentr.io) Thanks!

Thanks for the reply. We are already following this up with our sergio and anthony .

**Comment by ArnauKokoro** [comment]
Same here!

It's been two weeks looking for the problem. It begins when we were forced by Android to update from API 31 to API 33.

For more info I'll share on [stefan@sentr.io](mailto:stefan@sentr.io) a series of errores we are having.

Thanks!

**Comment by bitsandfoxes** [comment]
This has not been forgotten. We're still looking into it.

**Comment by matanplay** [comment]
same thing for us, i managed to reproduce the issue constantly on Realme 10 device and Motorola G100. Sentry causes crash about 1-2 minutes into gameplay. started when we were forced by google to target API level 33 two months ago.
mobile game using unity 2021.3.f29
Sentry Unity SDK versions 1.5.0/1.6.0/1.7.0
we have other plugins such as Mixpanel, Firebase & Singular.
when we created a build that has all of them but with Sentry removed, the game stopped crashing.
this is a serious issue and it would be a shame if we had to stop using Sentry.

please do everything that you can to resolve this ASAP. thanks

i hope that the following screenshots will provide your developers with some insights. also i hope that if you get a hold on the devices mentioned above, they will have an easier time reproducing and resolving - notice the devices there cause those devices reproduce constantly.
![image](https://github.com/getsentry/sentry-unity/assets/127018453/64263cd0-c0db-4fc4-8fb8-cff7d7c9144a)
![image](https://github.com/getsentry/sentry-unity/assets/127018453/6a9821bf-958f-49b9-875b-a7271975cada)
![image](https://github.com/getsentry/sentry-unity/assets/127018453/6aeb1ddc-c192-4dec-873a-a84e7ced3ba0)

**Comment by kahest** [comment]
Hi @matanplay, thank you for providing additional info and datapoints, we appreciate it! 
Solving this and the underlying https://github.com/getsentry/sentry-java/issues/2955 is top priority for us, and we're working with a team of several engineers, and collaborate closely with Google engineers. As noted in the linked issue, we made progress in creating a promising repro and possible solution that we are validating at the moment.

**Comment by kahest** [comment]
We just released [sentry-unity 1.7.1-beta.1](https://github.com/getsentry/sentry-unity/releases/tag/1.7.1-beta.1) with a fix for this issue. Our tests show very promising results, but we released this as a beta to get some more data. Please try out the beta if you can and let us know the results. 🙏

**Comment by matanplay** [comment]
thanks Karl
i will be testing this soon and will let you know

**Comment by matanplay** [comment]
Hi Karl,
I finished testing on the beta version.
it indeed didn't crash and it shows promise. but I did get an occasional
"hiccups" in the game (short frame freeze) that don't happen to us on other
builds where the Sentry SDK is disabled.
so while i will be using this beta version to release, i do suggest that
sentry developers continue looking for the function that might be CPU
intensive or creates an endless recursion

**Comment by kahest** [comment]
Hi @matanplay, thank you for reporting back, good to hear that the crashes are fixed!

The freezes are very likely not related to this update, but we'd appreciate if you could create an issue with some details so we can investigate further.

**Comment by matanplay** [comment]
Hi Karl,
I was wondering if I could get a tutorial regarding how to integrate the
source code of the SDK instead of the compiled one.
this could help me help you :-) (since the issue is reproducible on my
device and i can also profile the culprit)

**Comment by bitsandfoxes** [comment]
@matanplay Unfortunately, with the Unity SDK bundling all kinds of different SDKs under the hood the setup is not as straightforward as I'd like it to be. We do have [contributing docs](https://github.com/getsentry/sentry-unity/blob/main/CONTRIBUTING.md) regarding the setup tho.

**Comment by ShreyasRam** [comment]
Any rough estimate when a stable version can be rolled out?

**Comment by tmfconan** [comment]
We updated to the latest beta release for Unity (1.7.1-beta.1) and are still seeing crashes.

This is since we released:
![Screenshot 2023-11-16 at 3 41 58 PM](https://github.com/getsentry/sentry-unity/assets/2471934/a933ec14-fb39-4ca4-b3fd-cc4b998499a1)

This is since it started in mid-September:
![Screenshot 2023-11-16 at 3 37 43 PM](https://github.com/getsentry/sentry-unity/assets/2471934/f07a6a6e-909d-4524-a5ee-a379a07f16ba)

Thanks for looking into this!

**Comment by kahest** [comment]
Hi @tmfconan - can you share more information like Unity versions and Sentry SDK versions used before/after? Also can you share links to Sentry events for these crashes with me at karl.struggl@sentry.io?

**Comment by matanplay** [comment]
Hi @tmfconan did you try to do a release without any sentry SDK? I suggested you do that, even for a subset of your users , this will help you understand of the issues is just the Sentry SDK, or that there maybe other issues in your projects beside the known Sentry issuse

**Comment by tmfconan** [comment]
Hi @matanplay thanks for the response. Yes, we removed the Sentry package and the crashes have stopped.  I've sent info to @kahest. Hopefully it's helpful.

**Comment by kahest** [comment]
@tmfconan replied
@ShreyasRam we hope to get some more reports in during the next few days - in any case, we don't expect the fix to have any adverse effect, so we will likely release as stable next week

**Comment by aengmo1** [comment]
Any updates here on when a new version of sentry can be out with a fix?

**Comment by kahest** [comment]
Hey @aengmo1, expect a stable release of `sentry-unity` with the fix this week.

**Comment by matanplay** [comment]
@kahest using the latest **1.7.1** sdk has returned all crashes in an even a more aggressive manner.
so we reverted back to **1.7.1-beta** and that resolved everything for us.
I think the bug should be re-opened

**Comment by tmfconan** [comment]
I hate to pile on here, but crashes subsided slightly with the fix (both 1.7.1-beta and 1.7.1) but still 20% crash rates. Removing sentry fixes it. Unfortunately, I don't have any crash data in Sentry with the patched versions -- but crashlytics shows them.

**Comment by bitsandfoxes** [comment]
Hey @matanplay and @tmfconan. Thanks for getting back to us. We're taking this very seriously. 
I take it you also have events captured by Sentry as well? Could you confirm that those are getting captured by `sentry.native.android.unity` version `0.6.7`? It's the last entry at the bottom of the issue page?

**Comment by matanplay** [comment]
@bitsandfoxes sadly I can't find the error in our sentry logs, only in our crashlytics logs. also, we upgraded from the beta 1.7.1 to the final version during this current sprint, and while testing on Staging environment on devices that reproduced the issue in the past, we saw the crashes came back, so we just reverted back to the beta and all the crashes went silent

**Comment by bruno-garcia** [comment]
We definitely want to fix this if it's causing you issues, but I believe folks might need more details.
Could you share some details about the crashes? Like Android Tombstone, logcat output, etc?
A repro so we can debug locally would be amazing.

If you have something that's not possible to share publicly on GitHub, my email is bruno at sentry dot io

**Comment by kahest** [comment]
> I hate to pile on here, but crashes subsided slightly with the fix (both 1.7.1-beta and 1.7.1) but still 20% crash rates. Removing sentry fixes it. Unfortunately, I don't have any crash data in Sentry with the patched versions -- but crashlytics shows them.

@tmfconan this is very likely (still) a different root cause - could you create a separate GH issue for that please?

**Comment by matanplay** [comment]
@bruno-garcia - I don't have data I can share now, but I could create a specific build and reproduce the error with it. 
then I will be able to send you logcat logs (I am not familiar with tombstone). I will try to do this before the end of the week

**Comment by supervacuus** [comment]
> then I will be able to send you logcat logs (I am not familiar with tombstone). I will try to do this before the end of the week

Thanks @matanplay! If you can interact with your device via `adb`, you can execute 
```
$ adb bugreport
``` 
after a crash, which will download crash-relevant context from the device as a zip file. In the zip file under the path `/FS/data/tombstones,` you can find the tombstones, a collection of stack traces, memory views, memory mappings of all loaded binaries, open file descriptors, etc., which provide much more insight than `logcat` (although these logs are also often helpful).

**Comment by bitsandfoxes** [comment]
I'm looking for help in following up on this. As of now, I have not been able to reproduce the issue with the Unity SDK versions `1.7.1-beta` or newer.

**Comment by flashup** [comment]
Hello, we have similar crashes.

**Environment**
How do you use Sentry?
self-hosted Sentry 22.10.0

**Which version of the SDK?**
1.8.0

**How did you install the package?**
git url

**Which version of Unity?**
2022.3.17

**Is this happening in Unity (editor) or on a player like Android, iOS, Windows?**
Android

**Steps to Reproduce**
In our case most crashes happen when the application is unpausing (returns from background in foreground mode).
With disabled SentrySDK the crash is gone.

**Any logs or screenshots**
```
Exception Type: Unknown (SIGSEGV)

Application Specific Information:
Segfault

Thread 0 Crashed:
0   <unknown>                       0x0                 <unknown>
1   boot.oat                        0x7115e168          <unknown> + 1897259368
EOF
```

And we managed to catch the crash on development build:
```
02-02 17:03:24.072: A/DEBUG(19305):       #00 pc 0000000000000000  <unknown>
02-02 17:03:24.072: A/DEBUG(19305):       #01 pc 000000000201e984  /memfd:/jit-cache (deleted) (java.io.BufferedWriter.write+228)
02-02 17:03:24.072: A/DEBUG(19305):       #02 pc 0000000002012980  /memfd:/jit-cache (deleted) (io.sentry.vendor.gson.stream.JsonWriter.string+352)
02-02 17:03:24.072: A/DEBUG(19305):       #03 pc 00000000020219a0  /memfd:/jit-cache (deleted) (io.sentry.vendor.gson.stream.JsonWriter.value+128)
02-02 17:03:24.072: A/DEBUG(19305):       #04 pc 000000000202cd00  /memfd:/jit-cache (deleted) (io.sentry.JsonObjectWriter.value+64)
02-02 17:03:24.072: A/DEBUG(19305):       #05 pc 0000000002036b30  /memfd:/jit-cache (deleted) (io.sentry.JsonObjectWriter.value+48)
```

<details>
  <summary>Full log</summary>

  ```
  02-02 17:03:24.072: A/DEBUG(19305): backtrace:
  02-02 17:03:24.072: A/DEBUG(19305):       #00 pc 0000000000000000  <unknown>
  02-02 17:03:24.072: A/DEBUG(19305):       #01 pc 000000000201e984  /memfd:/jit-cache (deleted) (java.io.BufferedWriter.write+228)
  02-02 17:03:24.072: A/DEBUG(19305):       #02 pc 0000000002012980  /memfd:/jit-cache (deleted) (io.sentry.vendor.gson.stream.JsonWriter.string+352)
  02-02 17:03:24.072: A/DEBUG(19305):       #03 pc 00000000020219a0  /memfd:/jit-cache (deleted) (io.sentry.vendor.gson.stream.JsonWriter.value+128)
  02-02 17:03:24.072: A/DEBUG(19305):       #04 pc 000000000202cd00  /memfd:/jit-cache (deleted) (io.sentry.JsonObjectWriter.value+64)
  02-02 17:03:24.072: A/DEBUG(19305):       #05 pc 0000000002036b30  /memfd:/jit-cache (deleted) (io.sentry.JsonObjectWriter.value+48)
  02-02 17:03:24.072: A/DEBUG(19305):       #06 pc 0000000000137334  /apex/com.android.runtime/lib64/libart.so (art_quick_invoke_stub+548) (BuildId: 8fab55c3ae576efb1a33ea41d3593be6)
  02-02 17:03:24.072: A/DEBUG(19305):       #07 pc 00000000001460ac  /apex/com.android.runtime/lib64/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+244) (BuildId: 8fab55c3ae576efb1a33ea41d3593be6)
  02-02 17:03:24.072: A/DEBUG(19305):       #08 pc 00000000002e4db0  /apex/com.android.runtime/lib64/libart.so (art::interpreter::ArtInterpreterToCompiledCodeBridge(art::Thread*, art::ArtMethod*, art::ShadowFrame*, unsigned short, art::JValue*)+384) (BuildId: 8fab55c3ae576efb1a33ea41d3593be6)
  02-02 17:03:24.072: A/DEBUG(19305):       #09 pc 00000000002dfe3c  /apex/com.android.runtime/lib64/libart.so (bool art::interpreter::DoCall<false, false>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*)+900) (BuildId: 8fab55c3ae576efb1a33ea41d3593be6)
  02-02 17:03:24.072: A/DEBUG(19305):       #10 pc 00000000005a41a4  /apex/com.android.runtime/lib64/libart.so (MterpInvokeInterface+868) (BuildId: 8fab55c3ae576efb1a33ea41d3593be6)
  02-02 17:03:24.072: A/DEBUG(19305):       #11 pc 0000000000131a14  /apex/com.android.runtime/lib64/libart.so (mterp_op_invoke_interface+20) (BuildId: 8fab55c3ae576efb1a33ea41d3593be6)
  02-02 17:03:24.072: A/DEBUG(19305):       #12 pc 0000000000385ce8  [anon:dalvik-classes.dex extracted in memory from /data/app/com.APP_BUNDLE_ID-y87oRYXz_a6PX3inEtYOJQ==/base.apk] (io.sentry.protocol.Gpu.serialize+92)
  02-02 17:03:24.072: A/DEBUG(19305):       #13 pc 00000000002b56e0  /apex/com.android.runtime/lib64/libart.so (_ZN3art11interpreterL7ExecuteEPNS_6ThreadERKNS_20CodeItemDataAccessorERNS_11ShadowFrameENS_6JValueEbb.llvm.9123860073240645759+240) (BuildId: 8fab55c3ae576efb1a33ea41d3593be6)
  02-02 17:03:24.072: A/DEBUG(19305):       #14 pc 0000000000593ea8  /apex/com.android.runtime/lib64/libart.so (artQuickToInterpreterBridge+1024) (BuildId: 8fab55c3ae576efb1a33ea41d3593be6)
  02-02 17:03:24.072: A/DEBUG(19305):       #15 pc 0000000000140468  /apex/com.android.runtime/lib64/libart.so (art_quick_to_interpreter_bridge+88) (BuildId: 8fab55c3ae576efb1a33ea41d3593be6)
  02-02 17:03:24.072: A/DEBUG(19305):       #16 pc 000000000203acc0  /memfd:/jit-cache (deleted) (io.sentry.JsonObjectSerializer.serialize+1616)
  02-02 17:03:24.072: A/DEBUG(19305):       #17 pc 0000000000137334  /apex/com.android.runtime/lib64/libart.so (art_quick_invoke_stub+548) (BuildId: 8fab55c3ae576efb1a33ea41d3593be6)
  02-02 17:03:24.072: A/DEBUG(19305):       #18 pc 00000000001460ac  /apex/com.android.runtime/lib64/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+244) (BuildId: 8fab55c3ae576efb1a33ea41d3593be6)
  02-02 17:03:24.072: A/DEBUG(19305):       #19 pc 00000000002e4db0  /apex/com.android.runtime/lib64/libart.so (art::interpreter::ArtInterpreterToCompiledCodeBridge(art::Thread*, art::ArtMethod*, art::ShadowFrame*, unsigned short, art::JValue*)+384) (BuildId: 8fab55c3ae576efb1a33ea41d3593be6)
  02-02 17:03:24.072: A/DEBUG(19305):       #20 pc 00000000002dfe3c  /apex/com.android.runtime/lib64/libart.so (bool art::interpreter::DoCall<false, false>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*)+900) (BuildId: 8fab55c3ae576efb1a33ea41d3593be6)
  02-02 17:03:24.072: A/DEBUG(19305):       #21 pc 00000000005a2a10  /apex/com.android.runtime/lib64/libart.so (MterpInvokeVirtual+648) (BuildId: 8fab55c3ae576efb1a33ea41d3593be6)
  02-02 17:03:24.072: A/DEBUG(19305):       #22 pc 0000000000131814  /apex/com.android.runtime/lib64/libart.so (mterp_op_invoke_virtual+20) (BuildId: 8fab55c3ae576efb1a33ea41d3593be6)
  02-02 17:03:24.072: A/DEBUG(19305):       #23 pc 000000000034e108  [anon:dalvik-classes.dex extracted in memory from /data/app/com.APP_BUNDLE_ID-y87oRYXz_a6PX3inEtYOJQ==/base.apk] (io.sentry.JsonObjectWriter.value+4)
  02-02 17:03:24.072: A/DEBUG(19305):       #24 pc 00000000005a2d20  /apex/com.android.runtime/lib64/libart.so (MterpInvokeVirtual+1432) (BuildId: 8fab55c3ae576efb1a33ea41d3593be6)
  02-02 17:03:24.072: A/DEBUG(19305):       #25 pc 0000000000131814  /apex/com.android.runtime/lib64/libart.so (mterp_op_invoke_virtual+20) (BuildId: 8fab55c3ae576efb1a33ea41d3593be6)
  02-02 17:03:24.072: A/DEBUG(19305):       #26 pc 000000000034e270  [anon:dalvik-classes.dex extracted in memory from /data/app/com.APP_BUNDLE_ID-y87oRYXz_a6PX3inEtYOJQ==/base.apk] (io.sentry.JsonObjectWriter.value)
  02-02 17:03:24.072: A/DEBUG(19305):       #27 pc 00000000005a450c  /apex/com.android.runtime/lib64/libart.so (MterpInvokeInterface+1740) (BuildId: 8fab55c3ae576efb1a33ea41d3593be6)
  02-02 17:03:24.072: A/DEBUG(19305):       #28 pc 0000000000131a14  /apex/com.android.runtime/lib64/libart.so (mterp_op_invoke_interface+20) (BuildId: 8fab55c3ae576efb1a33ea41d3593be6)
  02-02 17:03:24.072: A/DEBUG(19305):       #29 pc 00000000003828bc  [anon:dalvik-classes.dex extracted in memory from /data/app/com.APP_BUNDLE_ID-y87oRYXz_a6PX3inEtYOJQ==/base.apk] (io.sentry.protocol.Contexts.serialize+80)
  02-02 17:03:24.072: A/DEBUG(19305):       #30 pc 00000000002b56e0  /apex/com.android.runtime/lib64/libart.so (_ZN3art11interpreterL7ExecuteEPNS_6ThreadERKNS_20CodeItemDataAccessorERNS_11ShadowFrameENS_6JValueEbb.llvm.9123860073240645759+240) (BuildId: 8fab55c3ae576efb1a33ea41d3593be6)
  02-02 17:03:24.072: A/DEBUG(19305):       #31 pc 0000000000593ea8  /apex/com.android.runtime/lib64/libart.so (artQuickToInterpreterBridge+1024) (BuildId: 8fab55c3ae576efb1a33ea41d3593be6)
  02-02 17:03:24.072: A/DEBUG(19305):       #32 pc 0000000000140468  /apex/com.android.runtime/lib64/libart.so (art_quick_to_interpreter_bridge+88) (BuildId: 8fab55c3ae576efb1a33ea41d3593be6)
  02-02 17:03:24.072: A/DEBUG(19305):       #33 pc 000000000203acc0  /memfd:/jit-cache (deleted) (io.sentry.JsonObjectSerializer.serialize+1616)
  02-02 17:03:24.072: A/DEBUG(19305):       #34 pc 0000000000137334  /apex/com.android.runtime/lib64/libart.so (art_quick_invoke_stub+548) (BuildId: 8fab55c3ae576efb1a33ea41d3593be6)
  02-02 17:03:24.072: A/DEBUG(19305):       #35 pc 00000000001460ac  /apex/com.android.runtime/lib64/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+244) (BuildId: 8fab55c3ae576efb1a33ea41d3593be6)
  02-02 17:03:24.072: A/DEBUG(19305):       #36 pc 00000000002e4db0  /apex/com.android.runtime/lib64/libart.so (art::interpreter::ArtInterpreterToCompiledCodeBridge(art::Thread*, art::ArtMethod*, art::ShadowFrame*, unsigned short, art::JValue*)+384) (BuildId: 8fab55c3ae576efb1a33ea41d3593be6)
  02-02 17:03:24.072: A/DEBUG(19305):       #37 pc 00000000002dfe3c  /apex/com.android.runtime/lib64/libart.so (bool art::interpreter::DoCall<false, false>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*)+900) (BuildId: 8fab55c3ae576efb1a33ea41d3593be6)
  02-02 17:03:24.072: A/DEBUG(19305):       #38 pc 00000000005a2a10  /apex/com.android.runtime/lib64/libart.so (MterpInvokeVirtual+648) (BuildId: 8fab55c3ae576efb1a33ea41d3593be6)
  02-02 17:03:24.072: A/DEBUG(19305):       #39 pc 0000000000131814  /apex/com.android.runtime/lib64/libart.so (mterp_op_invoke_virtual+20) (BuildId: 8fab55c3ae576efb1a33ea41d3593be6)
  02-02 17:03:24.072: A/DEBUG(19305):       #40 pc 000000000034e108  [anon:dalvik-classes.dex extracted in memory from /data/app/com.APP_BUNDLE_ID-y87oRYXz_a6PX3inEtYOJQ==/base.apk] (io.sentry.JsonObjectWriter.value+4)
  02-02 17:03:24.072: A/DEBUG(19305):       #41 pc 00000000005a2d20  /apex/com.android.runtime/lib64/libart.so (MterpInvokeVirtual+1432) (BuildId: 8fab55c3ae576efb1a33ea41d3593be6)
  02-02 17:03:24.072: A/DEBUG(19305):       #42 pc 0000000000131814  /apex/com.android.runtime/lib64/libart.so (mterp_op_invoke_virtual+20) (BuildId: 8fab55c3ae576efb1a33ea41d3593be6)
  02-02 17:03:24.072: A/DEBUG(19305):       #43 pc 000000000034f058  [anon:dalvik-classes.dex extracted in memory from /data/app/com.APP_BUNDLE_ID-y87oRYXz_a6PX3inEtYOJQ==/base.apk] (io.sentry.JsonSerializer.serialize+140)
  02-02 17:03:24.072: A/DEBUG(19305):       #44 pc 00000000005a450c  /apex/com.android.runtime/lib64/libart.so (MterpInvokeInterface+1740) (BuildId: 8fab55c3ae576efb1a33ea41d3593be6)
  02-02 17:03:24.072: A/DEBUG(19305):       #45 pc 0000000000131a14  /apex/com.android.runtime/lib64/libart.so (mterp_op_invoke_interface+20) (BuildId: 8fab55c3ae576efb1a33ea41d3593be6)
  02-02 17:03:24.072: A/DEBUG(19305):       #46 pc 000000000037bbc4  [anon:dalvik-classes.dex extracted in memory from /data/app/com.APP_BUNDLE_ID-y87oRYXz_a6PX3inEtYOJQ==/base.apk] (io.sentry.cache.CacheUtils.store+188)
  02-02 17:03:24.072: A/DEBUG(19305):       #47 pc 00000000005a58b0  /apex/com.android.runtime/lib64/libart.so (MterpInvokeStatic+1136) (BuildId: 8fab55c3ae576efb1a33ea41d3593be6)
  02-02 17:03:24.072: A/DEBUG(19305):       #48 pc 0000000000131994  /apex/com.android.runtime/lib64/libart.so (mterp_op_invoke_static+20) (BuildId: 8fab55c3ae576efb1a33ea41d3593be6)
  02-02 17:03:24.072: A/DEBUG(19305):       #49 pc 000000000037d640  [anon:dalvik-classes.dex extracted in memory from /data/app/com.APP_BUNDLE_ID-y87oRYXz_a6PX3inEtYOJQ==/base.apk] (io.sentry.cache.PersistingScopeObserver.store+8)
  02-02 17:03:24.072: A/DEBUG(19305):       #50 pc 00000000005a50a8  /apex/com.android.runtime/lib64/libart.so (MterpInvokeDirect+1168) (BuildId: 8fab55c3ae576efb1a33ea41d3593be6)
  02-02 17:03:24.072: A/DEBUG(19305):       #51 pc 0000000000131914  /apex/com.android.runtime/lib64/libart.so (mterp_op_invoke_direct+20) (BuildId: 8fab55c3ae576efb1a33ea41d3593be6)
  02-02 17:03:24.072: A/DEBUG(19305):       #52 pc 000000000037d340  [anon:dalvik-classes.dex extracted in memory from /data/app/com.APP_BUNDLE_ID-y87oRYXz_a6PX3inEtYOJQ==/base.apk] (io.sentry.cache.PersistingScopeObserver.lambda$setContexts$9$io-sentry-cache-PersistingScopeObserver+4)
  02-02 17:03:24.072: A/DEBUG(19305):       #53 pc 00000000005a2d20  /apex/com.android.runtime/lib64/libart.so (MterpInvokeVirtual+1432) (BuildId: 8fab55c3ae576efb1a33ea41d3593be6)
  02-02 17:03:24.072: A/DEBUG(19305):       #54 pc 0000000000131814  /apex/com.android.runtime/lib64/libart.so (mterp_op_invoke_virtual+20) (BuildId: 8fab55c3ae576efb1a33ea41d3593be6)
  02-02 17:03:24.072: A/DEBUG(19305):       #55 pc 000000000037d0cc  [anon:dalvik-classes.dex extracted in memory from /data/app/com.APP_BUNDLE_ID-y87oRYXz_a6PX3inEtYOJQ==/base.apk] (io.sentry.cache.PersistingScopeObserver$$ExternalSyntheticLambda3.run+8)
  02-02 17:03:24.072: A/DEBUG(19305):       #56 pc 00000000005a450c  /apex/com.android.runtime/lib64/libart.so (MterpInvokeInterface+1740) (BuildId: 8fab55c3ae576efb1a33ea41d3593be6)
  02-02 17:03:24.072: A/DEBUG(19305):       #57 pc 0000000000131a14  /apex/com.android.runtime/lib64/libart.so (mterp_op_invoke_interface+20) (BuildId: 8fab55c3ae576efb1a33ea41d3593be6)
  02-02 17:03:24.072: A/DEBUG(19305):       #58 pc 000000000037d2dc  [anon:dalvik-classes.dex extracted in memory from /data/app/com.APP_BUNDLE_ID-y87oRYXz_a6PX3inEtYOJQ==/base.apk] (io.sentry.cache.PersistingScopeObserver.lambda$serializeToDisk$10$io-sentry-cache-PersistingScopeObserver)
  02-02 17:03:24.072: A/DEBUG(19305):       #59 pc 00000000005a2d20  /apex/com.android.runtime/lib64/libart.so (MterpInvokeVirtual+1432) (BuildId: 8fab55c3ae576efb1a33ea41d3593be6)
  02-02 17:03:24.072: A/DEBUG(19305):       #60 pc 0000000000131814  /apex/com.android.runtime/lib64/libart.so (mterp_op_invoke_virtual+20) (BuildId: 8fab55c3ae576efb1a33ea41d3593be6)
  02-02 17:03:24.072: A/DEBUG(19305):       #61 pc 000000000037d18c  [anon:dalvik-classes.dex extracted in memory from /data/app/com.APP_BUNDLE_ID-y87oRYXz_a6PX3inEtYOJQ==/base.apk] (io.sentry.cache.PersistingScopeObserver$$ExternalSyntheticLambda6.run+8)
  02-02 17:03:24.072: A/DEBUG(19305):       #62 pc 00000000005a450c  /apex/com.android.runtime/lib64/libart.so (MterpInvokeInterface+1740) (BuildId: 8fab55c3ae576efb1a33ea41d3593be6)
  02-02 17:03:24.072: A/DEBUG(19305):       #63 pc 0000000000131a14  /apex/com.android.runtime/lib64/libart.so (mterp_op_invoke_interface+20) (BuildId: 8fab55c3ae576efb1a33ea41d3593be6)
  02-02 17:03:24.072: A/DEBUG(19305):       #64 pc 00000000001e7200  /apex/com.android.runtime/javalib/core-oj.jar (java.util.concurrent.Executors$RunnableAdapter.call+4)
  02-02 17:03:24.072: A/DEBUG(19305):       #65 pc 00000000005a450c  /apex/com.android.runtime/lib64/libart.so (MterpInvokeInterface+1740) (BuildId: 8fab55c3ae576efb1a33ea41d3593be6)
  02-02 17:03:24.072: A/DEBUG(19305):       #66 pc 0000000000131a14  /apex/com.android.runtime/lib64/libart.so (mterp_op_invoke_interface+20) (BuildId: 8fab55c3ae576efb1a33ea41d3593be6)
  02-02 17:03:24.072: A/DEBUG(19305):       #67 pc 00000000001ed242  /apex/com.android.runtime/javalib/core-oj.jar (java.util.concurrent.FutureTask.run+62)
  02-02 17:03:24.072: A/DEBUG(19305):       #68 pc 00000000005a39c0  /apex/com.android.runtime/lib64/libart.so (MterpInvokeSuper+2312) (BuildId: 8fab55c3ae576efb1a33ea41d3593be6)
  02-02 17:03:24.072: A/DEBUG(19305):       #69 pc 0000000000131894  /apex/com.android.runtime/lib64/libart.so (mterp_op_invoke_super+20) (BuildId: 8fab55c3ae576efb1a33ea41d3593be6)
  02-02 17:03:24.072: A/DEBUG(19305):       #70 pc 00000000001f3c16  /apex/com.android.runtime/javalib/core-oj.jar (java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run+38)
  02-02 17:03:24.072: A/DEBUG(19305):       #71 pc 00000000005a450c  /apex/com.android.runtime/lib64/libart.so (MterpInvokeInterface+1740) (BuildId: 8fab55c3ae576efb1a33ea41d3593be6)
  02-02 17:03:24.072: A/DEBUG(19305):       #72 pc 0000000000131a14  /apex/com.android.runtime/lib64/libart.so (mterp_op_invoke_interface+20) (BuildId: 8fab55c3ae576efb1a33ea41d3593be6)
  02-02 17:03:24.072: A/DEBUG(19305):       #73 pc 00000000001f828a  /apex/com.android.runtime/javalib/core-oj.jar (java.util.concurrent.ThreadPoolExecutor.runWorker+158)
  02-02 17:03:24.072: A/DEBUG(19305):       #74 pc 00000000005a2d20  /apex/com.android.runtime/lib64/libart.so (MterpInvokeVirtual+1432) (BuildId: 8fab55c3ae576efb1a33ea41d3593be6)
  02-02 17:03:24.072: A/DEBUG(19305):       #75 pc 0000000000131814  /apex/com.android.runtime/lib64/libart.so (mterp_op_invoke_virtual+20) (BuildId: 8fab55c3ae576efb1a33ea41d3593be6)
  02-02 17:03:24.072: A/DEBUG(19305):       #76 pc 00000000001f7038  /apex/com.android.runtime/javalib/core-oj.jar (java.util.concurrent.ThreadPoolExecutor$Worker.run+4)
  02-02 17:03:24.072: A/DEBUG(19305):       #77 pc 00000000005a450c  /apex/com.android.runtime/lib64/libart.so (MterpInvokeInterface+1740) (BuildId: 8fab55c3ae576efb1a33ea41d3593be6)
  02-02 17:03:24.072: A/DEBUG(19305):       #78 pc 0000000000131a14  /apex/com.android.runtime/lib64/libart.so (mterp_op_invoke_interface+20) (BuildId: 8fab55c3ae576efb1a33ea41d3593be6)
  02-02 17:03:24.072: A/DEBUG(19305):       #79 pc 00000000000ea9d8  /apex/com.android.runtime/javalib/core-oj.jar (java.lang.Thread.run+8)
  02-02 17:03:24.073: A/DEBUG(19305):       #80 pc 00000000002b56e0  /apex/com.android.runtime/lib64/libart.so (_ZN3art11interpreterL7ExecuteEPNS_6ThreadERKNS_20CodeItemDataAccessorERNS_11ShadowFrameENS_6JValueEbb.llvm.9123860073240645759+240) (BuildId: 8fab55c3ae576efb1a33ea41d3593be6)
  02-02 17:03:24.073: A/DEBUG(19305):       #81 pc 0000000000593ea8  /apex/com.android.runtime/lib64/libart.so (artQuickToInterpreterBridge+1024) (BuildId: 8fab55c3ae576efb1a33ea41d3593be6)
  02-02 17:03:24.073: A/DEBUG(19305):       #82 pc 0000000000140468  /apex/com.android.runtime/lib64/libart.so (art_quick_to_interpreter_bridge+88) (BuildId: 8fab55c3ae576efb1a33ea41d3593be6)
  02-02 17:03:24.073: A/DEBUG(19305):       #83 pc 0000000000137334  /apex/com.android.runtime/lib64/libart.so (art_quick_invoke_stub+548) (BuildId: 8fab55c3ae576efb1a33ea41d3593be6)
  02-02 17:03:24.073: A/DEBUG(19305):       #84 pc 00000000001460ac  /apex/com.android.runtime/lib64/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+244) (BuildId: 8fab55c3ae576efb1a33ea41d3593be6)
  02-02 17:03:24.073: A/DEBUG(19305):       #85 pc 00000000004b2f58  /apex/com.android.runtime/lib64/libart.so (art::(anonymous namespace)::InvokeWithArgArray(art::ScopedObjectAccessAlreadyRunnable const&, art::ArtMethod*, art::(anonymous namespace)::ArgArray*, art::JValue*, char const*)+104) (BuildId: 8fab55c3ae576efb1a33ea41d3593be6)
  02-02 17:03:24.073: A/DEBUG(19305):       #86 pc 00000000004b4008  /apex/com.android.runtime/lib64/libart.so (art::InvokeVirtualOrInterfaceWithJValues(art::ScopedObjectAccessAlreadyRunnable const&, _jobject*, _jmethodID*, jvalue const*)+416) (BuildId: 8fab55c3ae576efb1a33ea41d3593be6)
  02-02 17:03:24.073: A/DEBUG(19305):       #87 pc 00000000004f4558  /apex/com.android.runtime/lib64/libart.so (art::Thread::CreateCallback(void*)+1176) (BuildId: 8fab55c3ae576efb1a33ea41d3593be6)
  02-02 17:03:24.073: A/DEBUG(19305):       #88 pc 00000000000e24a4  /apex/com.android.runtime/lib64/bionic/libc.so (__pthread_start(void*)+36) (BuildId: ceedf0f98da575de138b0c631aceca44)
  02-02 17:03:24.073: A/DEBUG(19305):       #89 pc 0000000000083d98  /apex/com.android.runtime/lib64/bionic/libc.so (__start_thread+64) (BuildId: ceedf0f98da575de138b0c631aceca44)
  ```

</details>

**Comment by markushi** [comment]
Hey @flashup, thanks for providing additional information and context! Are you able to reproduce this issue locally on one of your devices?
If so running
````shell
adb bugreport
````
and sharing the resulting .zip, which will contain the tombstones would help us a lot in understanding the issue better.

**Comment by flashup** [comment]
@markushi Sure, here is the [report.zip](https://github.com/getsentry/sentry-unity/files/14184295/report.zip)

**Comment by supervacuus** [comment]
Thanks for the report, @flashup; this is a different issue (tracking here: https://github.com/getsentry/sentry-unity/issues/1555)

**Comment by bitsandfoxes** [comment]
Considering this closed as any currently known issues have a different cause.
We're following this up https://github.com/getsentry/sentry-native/issues/961 to increase stability make sure we're not experiencing any regressions.
